import React from 'react'
import Head from 'next/head'

import Navbar from './Navbar'
import Footer from './Footer'

export default function Layout({children}) {
  return (
      <>
        <Head>
            <title>tuContaApp</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar></Navbar>
            {children}
        <Footer></Footer>
      </>
  )
}
